### ISSUE TITLE
2018 7월말 라이트닝 토크 이벤트

### ISSUE THREAD

**Issue by Rokt33r** [seouljs/seoul.js.org#14]
일단 임시로 올려둡니다. 얘기하면서 수정할게요!

---

# INFORMATION
💎 제목: Seoul.js 라이트닝 토크
📆 날짜: 7월 27일 19:00~22:00
🏠 장소: Koss Lab 서울시 강남구 테헤란로 311 아남타워빌딩 7층
📍 등록: festa.io
🏧 스폰서: [: TBD]
📛 아젠다/스케줄: [: TBD]

# TODO
- [x]  📆 날짜, 장소 확정
  - [x] 코스랩 연락 (리오)
- [x]   🎟 타이틀 선정, 미트업/컨퍼런스/서밋/세미나/등등등
  - Seoul.js 라이트닝 토크
- [ ]   🗣 스피커 확정
  - **7월 30**일까지 행사 컨셉 공유하고 seoule.js 슬랙 채널내에서 발표자 초대
- [x]   🎆 홈페이지, 안내페이지
  - [ ] Seoul.js 라이트닝 토크 안내페이지 (리오)
- [x]  📍신청페이지와 선정방법 유/무료여부
- [x]  📯 홍보
- [ ] 💰 스폰서 영업(응?)

# Meetings
2018.6.27 19:00 리오, 케빈, 준영

**Comment by Rokt33r** [comment]
이전에 올렸던 글을 기록용으로 다시 올립니다. 이벤트 공개시 일본 관련 얘기는 뺄 예정입니다.

---

서울.js에서 주최하는 라이트닝 토크 이벤트!

Javascript를 사랑하는 개발자들이 부담없이 기술에 대해 자유롭게 토론 할 수 있는 기회를 제공하려고 합니다. 5~10분 정도의 가벼운 프레젠테이션을 통하여 쉽게 아이스 브레이킹을 하고, 이후에 피자와 함께 네트워킹을 하는 시간을 가질 계획입니다.

왜 라이트닝 토크인가?

저는 일본에서 개발자 커리어를 시작해서 2년전 처음으로 한국에서 조금씩 활동을 시작했는데 한국과 일본의 개발자 이벤트 사이에 좀 커다란 차이를 발견했습니다.
일본의 경우에는 개발자 이벤트에서 발표가 종료후에 네트워킹 시간이 되면, 대부분 남아서 얘기를 주고 받았고, 심지어 발표자가 아닌 사람까지 작은 프레젠테이션을 준비해서 이 시간에까지 발표와 토론의 자유롭게 이어나가요.
반면 제가 한국에 귀국해서 이벤트를 참가했을때는 대부분의 개발자들이 발표이후에 금방 자리를 떠나서 이벤트의 주최측이 되지 않는 이상 네트워킹이 거의 힘든 느낌이었어요.

보통 일본사람들이 한국사람보다 처음 만난 사람과 얘기를 나누는걸 훨씬 어색해하는데, 왜 개발자 이벤트에서는 정반대의 현상이 일어날까 생각해보았는데, 그 작은 프레젠테이션의 유무가 엄청 크지 않을까 싶었어요.

작은 프레젠테이션은 어떤 효과를 가질까요?
우선 네트워킹의 허들이 엄청나게 줄어듭니다. 기존의 이벤트의 경우 발표자가 소수의 전문가에 한정되어 있는 만큼 그들과 얘기해볼 기회를 만들기가 어렵고, 이벤트 참가자 사이에서의 네트워킹도 서로 무엇에 관심있는 사람인지 모르기 때문에 매번 자기소개를 번복해야하는 문제가 생기죠. 반면 라이트닝 토크의 경우에는 대부분의 참가자들이 짧은 자기소개겸 발표를 하기 때문에 이미 서로 어디에 관심을 가지고 있는지 알 수 있으므로 매번 소개를 해야하는 부담이 훨씬 줄어듭니다.
게다가, 발표 시간이 짧은 만큼 10~20여장의 슬라이드면 충분하므로 스피커의 부담역시 매우 줄어듭니다. 발표 내용 역시 무언거 성과를 낸 얘기가 아니더라도 무언가 시도중이거나 컨샙 단계의 얘기로도 충분하다고 생각해요. 혹시 알까요? 누군가 더 나은 방식을 알려주거나 미리 문제를 막을 수 있을지.

**Comment by Rokt33r** [comment]
고려중인 후보 장소 KOSSLab / Maru180 / DCamp / 강남 Toz

**Comment by Rokt33r** [comment]
참가인원 : 발표자 15명, 청자 25명으로 총 40명

**Comment by Rokt33r** [comment]
기획을 다시 정리했습니다. 피드백이 매우 매우 매우 절실합니다!!

글의 수정제안은 구글독스로 해주세요!
https://docs.google.com/document/d/1rzuPBf5EPAwPg3h6jpx2uEBql1agClI-510bY1MrVRo/edit#

---

이번 서울js 라이트닝 토크에서는 네트워킹 중심의 이벤트를 열려고 합니다!

각자 5분정도의 매우 짧은 프레젠테이션을 통해서 가볍게 서로의 관심사를 공유하여 아이스 브레이킹을 하고, 발표가 다 끝나면 피자와 함께 자유롭게 네트워킹을 하는 시간을 가지려 합니다.

## 왜 이런 이벤트를 열려 하는가?

좀 더 개발자들이 서로간에 편하게 커뮤니케이션이 가능한 환경을 만들어보고 싶습니다. 대부분의 이벤트의 경우 소수의 전문가가 일방적으로 발표를 하고, 참가자들은 발표가 끝나면 네트워킹 없이 다들 집으로 가버리는 경우를 많이 보게 됩니다. 저희 생각에는 네트워킹의 허들이 많이 높아서 그렇다고 생각해요. 발표자가 소수인 만큼 그들과 직접 얘기해볼 수 있는 사람은 매우 제한되어있고, 참가자 사이에서도 각자 무엇에 관심있는지 전혀 모르기에 매번 자기 소개를 번복해야하는 불편함이 있습니다. 반면 이런 형식의 라이트닝 토크는 발표를 통해 자기 소개가 이루어지기 때문에 이미 서로 어디에 관심을 가지는지 알 수 있는만큼 직접 관심있는 사람을 찾아 나서는 부담이 확 줄어들게 되죠.
또 다른 점으로는 발표에 필요한 슬라이드가 10~20장인 만큼 발표자의 부담도 매우 줄어서 하루밤 사이에 충분히 준비 할 수 있고, 내용 역시 무언가 성과를 낸 얘기가 아니더라도 아직 계획중이거나 시도중인 아이디어를 공유하여 피드백을 받는 등 수업같은 일방적인 커뮤니케이션이 아니라 서로간에 아이디어를 주고 받을 수 있는 제대로된 커뮤니케이션이 가능해지지 않을까 기대하고 있습니다.

## 참가자에 대해서

참가자는 전부 40명으로 발표자 14명에 청자 26명으로 구성 될 계획입니다.
발표 내용은 JS와 관련되면 무엇이든 가능하고, 앞서 설명한것처럼 무언가를 만들면서 느낀 경험담이나 생각중인 계획등 자유롭게 얘기해주셨으면 합니다.
그리고 들으러 오신 참석자분들도 가볍게 발표거리가 있으시면 네트워킹 타임에 발표를 할 수 있는 기회를 드릴 계획입니다!

Javascript를 주로 사용하는 개발자
Seoul.js의 행동 강령에 따라주실 수 있는 분 https://seoul.js.org/seoul.js/code-of-conduct.html

**Comment by rhiokim** [comment]
- [ ] 처음 경험하는 사람들을 위해 **5분 정도의 매우 짧은 프리젠테이션**의 형태에 좀더 디테일한 예를 든 설명이 있으면 좋을것 같아요. (참고할만한 발표 자료나, 이벤트 등)
- [ ] 이벤트에 참여함으로써 얻을 수 있는 것들에 대해 나열식으로 문장에 추가해보면 더 좋을 것 같아요.

**Comment by Rokt33r** [comment]
@rhiokim 오늘 저녁에 준비해서 공유해드리겠습니다!

**Comment by rohjs** [comment]
- 참가자 모두가 (마음만 먹으면) 발표자가 될 수 있다는 것에 대해선 매우 좋은 아이디어라고 생각해요. 각자 자신에 대해 소개하는 게 자신이 행사에 **능동적으로 기여할 수 있는 무언가가 있다**는 느낌 전달이 좋아요!

- 개인적으로는 **라이트닝 토크 이벤트**라는 용어가 강연, 지식 공유의 뉘앙스가 더 강한 것 같아서, 행사의 목적을 좀더 명확하게 전달할 수 있는 브랜딩이나 키워드 등이 필요할 것 같아요. 앞서 말씀하셨듯이 이런  행사가 한국에서는 아직까진 익숙하지 않은 만큼, 무엇을 하는 행사인지에 대해 센스있게 전달을 해야할 것 같아요!

> ... 또 다른 점으로는 발표에 필요한 슬라이드가 10~20장인 만큼 _발표자의 부담도 매우 줄어서 하루밤 사이에 충분히 준비 할 수 있고,_ 내용 역시 무언가 성과를 낸 얘기가 아니더라도 아직 계획중이거나 시도중인 아이디어를 공유하여 피드백을 받는 등 수업같은 일방적인 커뮤니케이션이 아니라...

-  **아무나 쉽게 참가할 수 있다**가 가져올 수도 있는 단점?이 걱정이 됩니다. 뭔가 이런 행사를 개최하려고 하는 목적과 방향에 대해 공감할 수 있는 사람들이 모이면 더 의미있는 시간이 될 것 같은데, 어떻게 그런 분위기를 형성할 수 있을지 고민해보면 좋을 것 같아요!

**Comment by ragingwind** [comment]
수고많이하셨습니다.

**Comment by rhiokim** [comment]
발표자료 목록
- 나석주님: Angular CDK로 높은 퀄리티의 UI 개발하기
  - https://speakerdeck.com/seokjuna/angular-cdkro-nopeun-kweolritiyi-ui-gaebalhagi
- 방진호님:
- 한재엽님:
- 안도형님:
- 신정규님:
