### ISSUE TITLE
Seoul.js 미트업 201811

### ISSUE THREAD

**Issue by ragingwind** [seouljs/seoul.js.org#19]
# General Information

💎 제목: Seoul.js 미트업 2018, The year of Javascript in 2018
📆 날짜: [TBD] 2018 년 11 월 중
🏠 장소: [TBD]
📍 등록: Festa
🏧 스폰서: [TBD]
📛 아젠다/스케줄: [TBD]

# Concept

현재 Javascript 는 많은 분야에서 광범위하게 사용 되고 있습니다. 웹브라우저의 동작하는 어플리케이션에서 부터 머신러닝까지 다룰 수 있습니다. 그래서 올 한해, 2018 년을 마무리 하면서 올해에 있었던 Javascript 에 대한 내용을 카테고리를 나누어서 정리 해보는 시간을 마련했습니다. 

## [WIP] Category Proposals

- Languages: ES.next, Typescript, Flow and more
- Frameworks: React, Vuejs, Angular, Polymer, CSS solutions
- Platforms: Chrome/Safari/Firefox, Deno, Node.js, Blockchain
- Backends: Machine Learning, Backends, Cloud
- Native: Electron, Moun, React Native, Ionic, Vue Native
- Tooling: Prettier ...

## Online Streaming

이번 미트업의 가장 특징은 오프라인은 네트워킹과 특별한 경험을 제공하고, 유투브 채널을 통해서 스트리밍하고 비디오로 세션들을 공유할 수 있도록 서비스를 제공합니다.

## TODO

- [ ] 날짜, 장소 확정
- [ ] 스탭모집
- [ ] 카테고리와 내부 항목 선전
- [ ] 실시간 방송 준비
- [ ] CALL FOR SPEAKER
- [ ] 홈페이지, 안내페이지, 신청페이지
- [ ] 스웩 기획과 준비
- [ ] 홍보채널, 페이스북
- [ ] 스폰서 영업(응?)

**Comment by ragingwind** [comment]
홍보물 제작도 있을 것 같네요. 스티커나 포스터, 엑스밴드

**Comment by ragingwind** [comment]
WebX: WebVR, WebPayment, WebAssembly?

**Comment by rhiokim** [comment]
OSS: RailsGirls(Babel), JSGirls?, JS OSS Culture 
> 세션 1,2개 정도? - 1개라고 쓰면 정없을까봐 😅

**Comment by rhiokim** [comment]
개인적으로는 WebComponent + Design System(**Design Ops**) 에 좀 관심이 있고 반대로 위에 클라우드(cloud)  zeit, heroku, google firesbase/firestore 과 같이 **DevOps** 쪽도 JS 에 포커스해서 할 이야기가 있을것 같아서..

카테고리를 어떻게 분리 해야할지 몰라서 일단 생각만

Design + Web/Frontend/JS + Backend/Infrastructure  처럼 Web/Frontend/JS 와 연관된 영역의 교집합에 대한 이야기도 추가해보면 좋을것 같아요.

**Comment by rhiokim** [comment]
스웩
- 스티커
- 배찌
  - 행사마다 컬렉션이 될 수 있도록... ? _'10년 후에 컬렉션 10개 모았어요??? 인증샷 볼 수 있도록?'_
- JS Bag
- 코쁠소 인형?
- 티셔츠
  - Backer
- 파우치
- 충전케이블

**Comment by ragingwind** [comment]
> 개인적으로는 WebComponent + Design System(Design Ops) 에 좀 관심이 있고 반대로 위에 클라우드(cloud) zeit, heroku, google firesbase/firestore 과 같이 DevOps 쪽도 JS 에 포커스해서 할 이야기가 있을것 같아서..

카데고리 갯수는 작게 유지하고 하위 항목을 늘리면 될 것 같아요. DevOps 는 Backends, Design Ops 는 일단 Frameworks 에 넣으면 되지 않을까요?

**Comment by ragingwind** [comment]
- Progressive Web Apps: PWA, WebXXX(Web Assembly, WebVR, WebGL ...)
