### ISSUE TITLE
Seoul.js 미트업 201810

### ISSUE THREAD

**Issue by ragingwind** [seouljs/seoul.js.org#20]
# General Information

💎 제목: Seoul.js 미트업 2018, 자바스크립트와 오픈소스
📆 날짜: 2018 년 10 월 23 일 화요일
🏠 장소: 구글 캠퍼스 메인 홀
📍 등록: Festa
🏧 스폰서: [TBD]
📛 아젠다/스케줄: [TBD]

# [WIP] Concept

자바스크립트 생태계는 다른 언어 대비 오픈소스 사용비중이 높습니다. 매일 같이 사용하는 도구 부터 에디터, 프레임워크와 라이브러리 패키지 심지어 언어의 스팩까지 모두 공개되고 누구든지 참여할 수 있도록 열여 있습니다. 당연히 자바스크립트 개발자들에게는 오픈소스의 사용이 익숙하고 스스로도 오픈소스에 참여하고 싶을 것입니다. 그에 비해서 아직 자바스크립트만을 을 대상으로 오픈소스를 다룬 적이 없습니다.  그래서 Seoul.js 에서는 이번 미트업에서 오픈소스 참여의 경험을 가진분들을 모셔서 경험과 인사이트를 다른 자바스크립트 개발자들을 전달해서 오픈소스 참여를 독려해보려고 합니다.

## Online Streaming

이번 미트업에서는 실험적으로 유투브 생중계를 해보려고 합니다.

## TODO

- [x] 날짜, 장소 확정
- [ ] 스탭모집
- [x] 카테고리와 내부 항목 선전
- [ ] 실시간 방송 준비
- [x] CALL FOR SPEAKER
- [ ] 홈페이지, 안내페이지, 신청페이지
- [ ] 스웩 기획과 준비
- [x] 홍보채널, 페이스북
- [ ] 스폰서 영업(응?)

**Comment by ragingwind** [comment]
구글 캠퍼스 10/23일 PM 7 ~ 9:30 까지 신청했습니다.

**Comment by ragingwind** [comment]
장소 시간 확정 되었습니다.

**Comment by rhiokim** [comment]
seoul.js.org 안내페이지는 https://github.com/seouljs/seoul.js.org/blob/master/docs/meetups/2018.10.23.md

여기에 작업하고 있습니다. 부족한 내용(참가자 대상, 참여방법) 채워지면 퍼블리싱하도록 할께요.
