### ISSUE TITLE
Seoul.js 미트업

### ISSUE THREAD

**Issue by ragingwind** [seouljs/seoul.js.org#3]
## INFORMATION

- 💎 제목: Seoul.js 미트업
- 📆 날짜: 2017 년 8월 18 일, 금요일
- 🏠 장소: 마루 180 지하 1 층
- 📍 등록: [온오프믹스: TBD]
- 🏧 스폰서: N/A
- 📛 아젠다/스케줄
  1. [일렉트론에서 자바스크립트 소스 코드 보호하기 (Protecting Javascript Source Code in Electron) · Issue #8 · seouljs/voting](https://goo.gl/De6PyB) - @2woongjae 
  1. [Flybook CLI - Static Web Site Generator · Issue #3 · seouljs/voting](https://goo.gl/2zp96g) - @rhiokim 
  1. [새로운 자바스크립트 개발 도구의 시대 (Zero-Configuration Tooling) · Issue #1 · seouljs/voting](https://goo.gl/aLYqJR) - @ragingwind 
  1. [ES2017 (ES8) 소개 (Introduce ECMAScript® 2017 Language Specification) · Issue #15 · seouljs/voting](https://goo.gl/DVamRe)  - @onyoon7

## TODO

- [x] 📆 날짜, 장소 확정
- [x] 🎟 타이틀 선정, 미트업/컨퍼런스/서밋/세미나/등등등
- [x] 📔 세션 주제 선정
- [x] 🗣 스피커 확정
- [x] 🖌 BI 리뉴얼
- [x] 🎆  홈페이지, 안내페이지
- [x] 📍신청페이지와 선정방법 유/무료여부
- [x] 📯 홍보
- [x] 💰 스폰서 영업(응?)

### 10 July, 2017, Hangout

**Comment by bomho** [comment]
SeoulJS ice breaking time

**Comment by bomho** [comment]
빙하에서 녹은 서울 Js의 등장

**Comment by ragingwind** [comment]
- 타이틀: 타이틀를 지속 가능한 버전이 좋고 미트업이 무난. 이후에 볼륨이 커지는 행사 >500 컨퍼런스가 적당
- 세션 주제: 저희 정체성을 보여줄 수 있도록 주제가 다양했으면, js 가 커버 가능항 대부분의 영역, node.js 일반/서버/CLI, js framework, desktop(electron), mobile native(react), tooling or iot 
- 스피커: 오거나이저가 일부 쇼케이스로 맡고 주제가 재미있거나 최신, 프로젝트 오우너인 경우가 우선순위가 높힌다. 외부 섭외면 빨리 진행해야.
- BI: JS 와 서울 느낌이 들어나면 좋다. 단순할 수록 멋질 것 같다
- 홈페이지, 안내페이지: 기존 사이트에서 flybook 을 이용해서 하는 정도, 왼쪽 탭에 미트업들이 리스트업 되어서 히스토리가 쌓이게 되면 좋다. 다만 좀 더 커스터마이징 가능했으면. 담당자 할당필요
- 홍보: 제가 아는한은 홍보/안내페이지 나오면 페북의 각 그룹에 공유하는 정도가 적당
- 스폰서: 능력한계 🙅

**Comment by 2woongjae** [comment]
신청 방법 : 온오프믹스 같은거?? 아님 구글 폼??

**Comment by 2woongjae** [comment]
행사날 역할 분담

**Comment by ragingwind** [comment]
회의록입니다. 빠지거나 보충부분은 알려주세요
---
## 타이틀

- seoul.js 미트업

## 세션/주제/스피커

- 출사표 작성: 비전, 큰그림, 인사이트, 제너럴 컨퍼런스의 설립의도를 커버
- 오거나이저 3 + 스페셜 토픽 1, 총 4 개로 구성. 
- 각 오거나이저가 인사이트가 될 만한 주제 2개, 스페셜 토픽 1개를 모아서 이후 정리 > 7/14

## BI/포스터/홈페이지

- BI/포스터: 정체성, 비전을 포함한 버전 > 7/28
- 홈페이지: 최대한 리소스 안들이는 방법으로 BI 와 포스터로 승부

## 신청/홍보/진행

- 시작일 7/29
- 100>
- 온오프믹스 사용 + 노쇼방지
- 등록처리에 지원자 필요 (필수는 아님)
- 진행은 운영자
- 스폰서는 있으면 좋지만 이번은 패스

## 그외

- 비디오 촬영 알아보기
- 유튜브 채널 생성

**Comment by rhiokim** [comment]
마일스톤으로 모두 넣었습니다. - https://github.com/seouljs/voting/milestone/1

**Comment by rhiokim** [comment]
리포 voting 을 meetup 이나 seminar 그런걸로 변경하는게 어떨까요?
URL 이 `seouljs/voting/mileston` 형태보다 `seouljs/meetup/mileston/1` 이런 형태가 좀 낫지 싶네요.

**Comment by ragingwind** [comment]
네 좋습니다. 먼저 리스트업 한번 해봐요. 저는 이정도 생각나고

1. meetup: informal meeting
2. seminar
3. conference: formal meeting
4. meetings

전 meetings(복수) 로 해서 seouljs/meetings/milestones/meetup-20170818 이 좋을 것 같아요
